name: lung-u-net
channels:
  - pytorch
dependencies:
  - python=3.8.5
  - pytorch
  - torchvision
  - torchaudio
  - pyspark
  - numpy
  - toolz
  - matplotlib
  - dill
  - pandas
  - partd
  - bokeh
  - keras
  - tensorflow
  - pip:
    - Scrapy==2.7
    - requests==2.28.2
    - xlwings==0.30.0
    - lxml==4.9.2
    - beautifulsoup4==4.11.1
    - selenium
    - jupyter
    - scipy
    - scikit-learn
    - statsmodels
    - seaborn
    - opencv-python
    - tqdm
    - pydicom
    - scikit-image
